defaults: &defaults
  adapter: mysq
  adapter: postgresql
  username: postgres
  password: zyrafynaszafy
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: dmp_development

test:
  <<: *defaults
  database: dmp_test

production:
  <<: *defaults
  database: dmp_production


